#include "MFCoefficients.h"
#include <iostream>

void MFCoefficients::initializeFromTir(std::unordered_map<std::string, double> coefficients) {

    std::cout << "Initializing MFCoefficients from TIR file..." << std::endl;
    std::cout << "-----------------------------------------------------------------" << std::endl;

    static const std::unordered_map<std::string, double MFCoefficients::*> field_map = {
        {"UNLOADED_RADIUS", & MFCoefficients::UNLOADED_RADIUS_},
        {"WIDTH",           & MFCoefficients::WIDTH_},
        {"ASPECT_RATIO",    & MFCoefficients::ASPECT_RATIO_},
        {"RIM_RADIUS",      & MFCoefficients::RIM_RADIUS_},
        {"RIM_WIDTH",       & MFCoefficients::RIM_WIDTH_},
        {"MASS",            & MFCoefficients::MASS_},
        {"IXX",             & MFCoefficients::IXX_},
        {"IYY",             & MFCoefficients::IYY_},
        {"BELT_MASS",       & MFCoefficients::BELT_MASS_},
        {"BELT_IXX",        & MFCoefficients::BELT_IXX_},
        {"BELT_IYY",        & MFCoefficients::BELT_IYY_},
        {"FNOMIN",          & MFCoefficients::FNOMIN_},
        {"LONGVL",          & MFCoefficients::LONGVL_},
        {"LFZO",            & MFCoefficients::LFZO_},
        {"LCX",             & MFCoefficients::LCX_},
        {"LMUX",            & MFCoefficients::LMUX_},
        {"LEX",             & MFCoefficients::LEX_},
        {"LKX",             & MFCoefficients::LKX_},
        {"LHX",             & MFCoefficients::LHX_},
        {"LVX",             & MFCoefficients::LVX_},
        {"LCY",             & MFCoefficients::LCY_},
        {"LMUY",            & MFCoefficients::LMUY_},
        {"LEY",             & MFCoefficients::LEY_},
        {"LKY",             & MFCoefficients::LKY_},
        {"LHY",             & MFCoefficients::LHY_},
        {"LRES",            & MFCoefficients::LRES_},
        {"LXAL",            & MFCoefficients::LXAL_},
        {"LYKA",            & MFCoefficients::LYKA_},
        {"LKYC",            & MFCoefficients::LKYC_},
        {"LKZC",            & MFCoefficients::LKZC_},
        {"LMY",             & MFCoefficients::LMY_},
        {"LVY",             & MFCoefficients::LVY_},
        {"PCX1",            & MFCoefficients::PCX1_},
        {"PDX1",            & MFCoefficients::PDX1_},
        {"PDX2",            & MFCoefficients::PDX2_},
        {"PEX1",            & MFCoefficients::PEX1_},
        {"PEX2",            & MFCoefficients::PEX2_},
        {"PEX3",            & MFCoefficients::PEX3_},
        {"PEX4",            & MFCoefficients::PEX4_},
        {"PKX1",            & MFCoefficients::PKX1_},
        {"PKX2",            & MFCoefficients::PKX2_},
        {"PKX3",            & MFCoefficients::PKX3_},
        {"PHX1",            & MFCoefficients::PHX1_},
        {"PHX2",            & MFCoefficients::PHX2_},
        {"PVX1",            & MFCoefficients::PVX1_},
        {"PVX2",            & MFCoefficients::PVX2_},
        {"QSY1",            & MFCoefficients::QSY1_},
        {"QSY2",            & MFCoefficients::QSY2_},
        {"QBZ1",            & MFCoefficients::QBZ1_},
        {"QBZ2",            & MFCoefficients::QBZ2_},
        {"QBZ3",            & MFCoefficients::QBZ3_},
        {"QBZ4",            & MFCoefficients::QBZ4_},
        {"QBZ5",            & MFCoefficients::QBZ5_},
        {"QBZ10",           & MFCoefficients::QBZ10_},
        {"QCZ1",            & MFCoefficients::QCZ1_},
        {"QDZ1",            & MFCoefficients::QDZ1_},
        {"QDZ2",            & MFCoefficients::QDZ2_},
        {"QDZ3",            & MFCoefficients::QDZ3_},
        {"QDZ4",            & MFCoefficients::QDZ4_},
        {"QDZ6",            & MFCoefficients::QDZ6_},
        {"QDZ7",            & MFCoefficients::QDZ7_},
        {"QDZ8",            & MFCoefficients::QDZ8_},
        {"QDZ9",            & MFCoefficients::QDZ9_},
        {"PPZ1",            & MFCoefficients::PPZ1_},
        {"PCY1",            & MFCoefficients::PCY1_},
        {"PDY1",            & MFCoefficients::PDY1_},
        {"PDY2",            & MFCoefficients::PDY2_},
        {"PDY3",            & MFCoefficients::PDY3_},
        {"PDYP1",           & MFCoefficients::PDYP1_},
        {"PDYP2",           & MFCoefficients::PDYP2_},
        {"PDYP3",           & MFCoefficients::PDYP3_},
        {"PDYP4",           & MFCoefficients::PDYP4_},
        {"PEY1",            & MFCoefficients::PEY1_},
        {"PEY2",            & MFCoefficients::PEY2_},
        {"PEY3",            & MFCoefficients::PEY3_},
        {"PEY4",            & MFCoefficients::PEY4_},
        {"PHY1",            & MFCoefficients::PHY1_},
        {"PHY2",            & MFCoefficients::PHY2_},
        {"PHY3",            & MFCoefficients::PHY3_},
        {"PKY1",            & MFCoefficients::PKY1_},
        {"PKY2",            & MFCoefficients::PKY2_},
        {"PKY3",            & MFCoefficients::PKY3_},
        {"PKYP1",           & MFCoefficients::PKYP1_},
        {"PVY1",            & MFCoefficients::PVY1_},
        {"PVY2",            & MFCoefficients::PVY2_},
        {"PVY3",            & MFCoefficients::PVY3_},
        {"PVY4",            & MFCoefficients::PVY4_},
        {"QDZ10",           & MFCoefficients::QDZ10_},
        {"QDZ11",           & MFCoefficients::QDZ11_},
        {"QEZ1",            & MFCoefficients::QEZ1_},
        {"QEZ2",            & MFCoefficients::QEZ2_},
        {"QEZ3",            & MFCoefficients::QEZ3_},
        {"QEZ4",            & MFCoefficients::QEZ4_},
        {"QEZ5",            & MFCoefficients::QEZ5_},
        {"QHZ1",            & MFCoefficients::QHZ1_},
        {"QHZ2",            & MFCoefficients::QHZ2_},
        {"QHZ3",            & MFCoefficients::QHZ3_},
        {"QHZ4",            & MFCoefficients::QHZ4_},
        {"QSX1",            & MFCoefficients::QSX1_},
        {"QSX10",           & MFCoefficients::QSX10_},
        {"QSX11",           & MFCoefficients::QSX11_},
        {"QSX12",           & MFCoefficients::QSX12_},
        {"QSX13",           & MFCoefficients::QSX13_},
        {"QSX14",           & MFCoefficients::QSX14_},
        {"QSX2",            & MFCoefficients::QSX2_},
        {"QSX3",            & MFCoefficients::QSX3_},
        {"RBX1",            & MFCoefficients::RBX1_},
        {"RBX2",            & MFCoefficients::RBX2_},
        {"RBY1",            & MFCoefficients::RBY1_},
        {"RBY2",            & MFCoefficients::RBY2_},
        {"RBY3",            & MFCoefficients::RBY3_},
        {"RCX1",            & MFCoefficients::RCX1_},
        {"RCY1",            & MFCoefficients::RCY1_},
        {"REX1",            & MFCoefficients::REX1_},
        {"REX2",            & MFCoefficients::REX2_},
        {"REY1",            & MFCoefficients::REY1_},
        {"REY2",            & MFCoefficients::REY2_},
        {"RHX1",            & MFCoefficients::RHX1_},
        {"RHY1",            & MFCoefficients::RHY1_},
        {"RHY2",            & MFCoefficients::RHY2_},
        {"RVY1",            & MFCoefficients::RVY1_},
        {"RVY2",            & MFCoefficients::RVY2_},
        {"RVY3",            & MFCoefficients::RVY3_},
        {"RVY4",            & MFCoefficients::RVY4_},
        {"RVY5",            & MFCoefficients::RVY5_},
        {"RVY6",            & MFCoefficients::RVY6_},
        {"SSZ1",            & MFCoefficients::SSZ1_},
        {"SSZ2",            & MFCoefficients::SSZ2_},
        {"SSZ3",            & MFCoefficients::SSZ3_},
        {"SSZ4",            & MFCoefficients::SSZ4_},
    };

    for (const auto& pair : coefficients) {
        auto it = field_map.find(pair.first);
        if (it != field_map.end()) {
            this->*(it->second) = pair.second;
            std::cout << "-- Value from CSV: " << pair.first << " = " << pair.second << std::endl;
            std::cout << "-- Member Variable: " << it->first << " = " << this->*(it->second) << std::endl;
        } else {
            std::cout << "Field not found: " << pair.first << ". Setting to zero..."<< std::endl;
            this->*(it->second) = 0.;

        }

        std::cout << "-----------------------------------------------------------------" << std::endl;
    }
}
